services:
  traefik:
    image: "traefik:3.3"
    command:
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --entrypoints.https.http3
      - --certificatesresolvers.leresolver.acme.tlschallenge=true
      - --certificatesresolvers.leresolver.acme.email=${LE_EMAIL}
      - --certificatesresolvers.leresolver.acme.storage=/certs/acme.json
      - --providers.swarm=true
      - --providers.swarm.endpoint=unix:///var/run/docker.sock
      - --providers.swarm.network=public
      - --providers.swarm.exposedbydefault=false
      - --log.level=ERROR
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    networks:
      - public
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/certs
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

networks:
  public:
    external: true

volumes:
  certs:
