services:
  factorio:
    image: factoriotools/factorio:latest
    environment:
      UPDATE_MODS_ON_START: "true"
    volumes:
      - /opt/factorio:/factorio
    networks:
      - traefik-public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.factorio==true
          - node.platform.arch==x86_64
      labels:
        - traefik.enable=true
        - traefik.udp.routers.factorio.entrypoints=factorio
        - traefik.udp.routers.factorio.service=factorio
        - traefik.udp.services.factorio.loadbalancer.server.port=34197

networks:
  traefik-public:
    external: true
