services:
  factorio:
    image: factoriotools/factorio:latest
    environment:
      UPDATE_MODS_ON_START: true
    volumes:
      - /opt/factorio:/factorio
    networks:
      - traefik_public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.factorio == true
      labels:
        - traefik.enable=true
        - traefik.udp.routers.factorio.entrypoints=factorio
        - traefik.udp.routers.factorio.service=factorio
        - traefik.udp.services.factorio.loadbalancer.server.port=34197

networks:
  traefik_public:
    external: true
