---
- name: Update packages
  hosts: nodes
  remote_user: user
  become: true
  become_user: root
  tasks:
    - name: Apt update
      ansible.builtin.apt:
        update_cache: true
        force_apt_get: true
        cache_valid_time: 3600

    - name: Apt upgrade
      ansible.builtin.apt:
        upgrade: dist
        force_apt_get: true

    - name: Check for reboot
      register: reboot_required_file
      ansible.builtin.stat:
        path: /var/run/reboot-required
        get_checksum: false

    - name: Reboot if required
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible after package updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists
